version: "3.4"
services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx
    restart: unless-stopped
    privileged: true
    environment:
      - MTX_API=yes
      - MTX_APIADDRESS=:9997
      - MTX_RECORD=yes
    volumes:
      - ./recordings:/recordings
    networks:
      - mtx
    ports:
      - 8554:8554
      - 8890:8890/udp
      - 1935:1935
      - 8888:8888
      - 8889:8889
      - 9997:9997
  mediamtx-connect:
    build:
      context: ./
    depends_on:
      - mediamtx
    container_name: mediamtx-connect
    restart: unless-stopped
    networks:
      - mtx
    volumes:
      - ./recordings:/recordings
    ports:
      - 3000:3000
  demo-streams:
    tty: true
    build:
      context: ./dev
    depends_on:
      - mediamtx
    container_name: demo-streams
    restart: unless-stopped
    networks:
      - mtx
networks:
  mtx:
    name: mtx
